# Generated by Django 2.2.3 on 2020-03-31 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prison_break_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='current_room',
        ),
        migrations.RemoveField(
            model_name='character',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='item_2',
        ),
        migrations.AddField(
            model_name='character',
            name='posx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='posy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='newGame',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_ID',
            field=models.IntegerField(default=0),
        ),
    ]
