# Generated by Django 2.2.3 on 2020-04-02 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prison_break_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='item_2',
        ),
        migrations.AddField(
            model_name='character',
            name='distracted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='escapeKey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='gametime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='posx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='posy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='spokeJ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='spokeT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='storeroomKey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='trophy1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='trophy2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='trophy3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='wardenKey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='newGame',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prevscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='userp',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
