# Generated by Django 2.2.3 on 2020-04-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison_break_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_room',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='distracted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='escapeKey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='gametime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='spokeJ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='spokeT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='storeroomKey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='trophy1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='trophy2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='trophy3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='wardenKey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hasCharacter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prevscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='userp',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
