# Generated by Django 2.2.3 on 2020-04-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_break_app', '0002_auto_20200402_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hasCharacter',
            field=models.IntegerField(default=0),
        ),
    ]
